Task us11 endpoint for retrieving unit fees 133
THE-390-Team/THE-390 pull request #166
Opened 2024-03-20 23:21 UTC by patrickmac3

- added view for calculating a companies revenue based on their properties and their property fees for units
- updated the endpoints accordingly 

related issue: #133

2024-03-20 23:46 UTC, NicholasWahome requested changes
- All tests must pass and implemented for this functionality.  Provide a screenshot from your terminal for this. 
- There are security and code duplications issue please review those in sonarcloud bot's review. 
- There is one file missing documentation please add that
- You have 41 commits but 2 lines of description on this pull request please make it reflective of all the changes you made

2024-03-20 23:46 UTC, NicholasWahome commented on backend/registration_key/migrations/0001_initial.py
> +
No documentation in this file

2024-03-21 00:20 UTC, NicholasWahome commented on backend/registration_key/migrations/0001_initial.py
> +
Resolved, because this is a migration file. Does not require documentation as it come prepackaged.

2024-03-21 01:22 UTC, patrickmac3 commented
code repitition is from frontend code which i am not involved with and is not new to this branch. 
for the email host password security issue, the password is okay being public because it will shortly be modified to fix an emailing issue and needs to be common to all members working on project

2024-03-21 01:23 UTC, closed without merging